name: deploy
on:
  push:
    branches:
      - release
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /srv/www/fastapi_app
            git pull origin main
            venv/bin/pip install -r requirements.txt
            venv/bin/python main.py initdb
            supervisorctl restart fastapi_app
